version: "3.4"

services:

  symfony:
    image: php:7.3-apache
    container_name: symfony
    volumes:
      - ./:/var/www/app
      - /docker/app.conf:/var/apache2/sites-available/000-default.conf
    tty: true
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${SYMFONY_DB_NAME}
      MYSQL_USER: ${SYMFONY_DB_USER}
      MYSQL_PASSWORD: ${SYMFONY_DB_PATH}
    ports:
      - "3307:3306"

volumes:
  db_data: